[tools]
deno = "latest"

[tasks.lint]
run = "deno lint --fix"

[tasks.format]
run = "deno fmt"

[tasks.run]
run = "deno run --allow-env --allow-net --allow-run --allow-sys --allow-read --allow-write main.ts"
